services:
  mysql:
    image: mysql:8.0.36
    container_name: patra-mysql
    restart: unless-stopped
    ports:
      - "13306:3306"
    environment:
      # 可放到 .env 中，这里直接写也可以
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/UTC
    command: >
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --lower_case_table_names=1
      --explicit_defaults_for_timestamp=ON
      --max_connections=300
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD:-root123456} -h 127.0.0.1 --silent" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0.15
    container_name: patra-redis
    restart: unless-stopped
    ports:
      - "16379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  default:
    name: patra-net
