server:
  port: 6000

spring:
  application:
    name: patra-registry

  config:
    import:
      - "optional:nacos:patra-registry.yaml?group=DEFAULT_GROUP&namespace=public"
      - "optional:nacos:patra.yaml?group=DEFAULT_GROUP&namespace=public"

  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource: # 数据库连接的 JDBC URL
      # - 3306 是 MySQL 的默认端口
      # - my_database 是你的数据库名
      # - ?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo 是为了保证字符编码正确和时区设置正确（推荐配置）
      url: jdbc:mysql://127.0.0.1:13306/patra_registry?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      # 数据库用户名
      username: root
      # 数据库密码
      password: 123456
      # JDBC 驱动类名 (对于新版 Spring Boot 和 JDBC 驱动，此项通常可以省略，它会自动推断)
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 配置 HikariCP 连接池 (默认的连接池, 以下为可选的性能调优配置)
      hikari:
        # 连接池中允许的最大连接数
        maximum-pool-size: 10
        # 连接池中保持的最小空闲连接数
        minimum-idle: 5
        # 等待数据库连接的最大时长，单位毫秒
        connection-timeout: 30000
        # 一个连接在池中空闲的最长时长，单位毫秒
        idle-timeout: 600000
        # 一个连接的最长生命周期，单位毫秒
        max-lifetime: 1800000
  flyway: # 是否启用 Flyway (默认为 true, 如果添加了 flyway-core 依赖)
      enabled: true
      # SQL 迁移脚本的位置, 多个位置用逗号隔开 (默认就是这个路径)
      locations: classpath:db/migration
      # 当迁移发现非空数据库时，是否自动执行 baseline (基线)，对于已存在的项目很有用
      baseline-on-migrate: true
      # 设置基线版本号，所有版本低于或等于此版本的迁移都将被忽略
      baseline-version: 0.1.0
  data:
    redis:
          url: redis://localhost:16379

# Error handling configuration
patra:
  error:
    enabled: true
    context-prefix: REG
  web:
    problem:
      enabled: true
      type-base-url: "https://errors.papertrace.com"
      include-stack: false
  feign:
    problem:
      enabled: true
      tolerant: true

