spring:
  application:
    name: patra-gateway

  config:
    import:
      - "optional:nacos:patra-gateway.yaml?group=DEFAULT_GROUP&namespace=public"

  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

    gateway:
      routes:
        - id: patra-ingest
          uri: lb://patra-ingest
          predicates:
            - Path=/patra-ingest/**
          filters:
            - StripPrefix=1

        - id: patra-registry
          uri: lb://patra-registry
          predicates:
            - Path=/patra-registry/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
server:
  port: 9528
